import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'User Guide',
      items: [
        {type: 'autogenerated', dirName: 'user-guide'},
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        'developer-guide/contributing',
      ],
    },
    {
      type: 'category',
      label: 'Release',
      items: [
        {type: 'autogenerated', dirName: 'release'},
      ],
    },
  ],
};

export default sidebars;
